# Generated by Django 5.1.2 on 2024-12-16 22:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Winner Name')),
                ('trivia_name', models.CharField(max_length=255, verbose_name='Trivia Name')),
                ('date_won', models.DateTimeField(auto_now_add=True, verbose_name='Date Won')),
                ('score', models.CharField(max_length=100, verbose_name='Score')),
            ],
            options={
                'ordering': ['-date_won'],
            },
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discord_channel', models.CharField(max_length=255, unique=True, verbose_name='Discord Channel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'LeaderBoard',
                'verbose_name_plural': 'LeaderBoards',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('points', models.IntegerField(verbose_name='points')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='score.leaderboard', verbose_name='LeaderBoard')),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
    ]
