# Generated by Django 5.1.2 on 2024-12-16 22:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Language Code')),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('is_public', models.BooleanField(default=True, help_text='Determines if the trivia is visible to all users', verbose_name='Is Public')),
                ('difficulty', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], verbose_name='Difficulty')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trivias_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivias', to='trivia.theme', verbose_name='Theme')),
                ('language', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trivias', to='trivia.language', verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=250, null=True, verbose_name='Question Title')),
                ('points', models.SmallIntegerField(default=10, verbose_name='Points')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('trivia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='trivia.trivia', verbose_name='Trivia')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_title', models.CharField(max_length=2502, null=True, verbose_name='Answer Title')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct Answer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='trivia.question', verbose_name='Question')),
                ('trivia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='trivia.trivia', verbose_name='Trivia')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trivia',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_trivia_title'),
        ),
    ]
